### PR TITLE
Basic User Interface 

### PR DESCRIPTION
**Pull request by CheetoLord**
created the layout for the home screen, did some styling, and also reorganized the filesystem a tad.

### CODE REVIEW

**Comment by lvym5** [comment]
Looks good!

**Review by kenny5033 — APPROVED** [review]
Looks great! Couple comments / questions that we can address in this PR or later, doesn't really matter:

Line 89: Why are we setting the search to empty string if a dish doesn't include the name?
Lines 92-96: This might be a prime place to use a one line ternary operator instead. 
`return (filtered.length == 0) ? defaultDishData : filtered;`

**Comment by kenny5033** [comment]
> this is not a set operation, its an equivalence check - just to ensure that every food item will match if the search bar is empty (not sure if the .includes would match empty string to everything)

I don't know why I wrote about setting stuff lol. What I meant to ask was why not just remove the or operations because includes("") is always true.

**Comment by CheetoLord** [comment]
> I don't know why I wrote about setting stuff lol. What I meant to ask was why not just remove the or operation because includes("") is always true.

Ah, gotcha. Ill go ahead and make these few edits rq then, it might make another pull rq in slack tho haha

**Pull request merged**
